# Generated by Django 2.2 on 2025-01-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180606_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_id',
        ),
    ]
